# Generated by Django 3.1.2 on 2020-10-25 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=50, verbose_name='用户车牌号')),
                ('user_choise', models.CharField(choices=[('0', '常规用户'), ('1', '会员')], max_length=10, verbose_name='是否会员')),
                ('user_starttime', models.DateTimeField(blank=True, null=True, verbose_name='停车时间')),
                ('user_endtime', models.DateTimeField(blank=True, null=True, verbose_name='结束停车时间')),
            ],
        ),
        migrations.CreateModel(
            name='VIPuserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nanme', models.CharField(max_length=30, verbose_name='用户昵称')),
                ('user_ID', models.CharField(max_length=50, unique=True, verbose_name='用户车牌号')),
                ('uer_rank', models.IntegerField(default=1, verbose_name='会员等级')),
                ('user_phone', models.CharField(max_length=20, verbose_name='用户手机号')),
                ('user_birth', models.DateField(verbose_name='用户出生年月日')),
                ('user_sex', models.CharField(max_length=6, verbose_name='用户性别')),
                ('user_grade', models.CharField(max_length=10, verbose_name='用户年龄')),
            ],
        ),
        migrations.CreateModel(
            name='user_charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_free', models.CharField(blank=True, max_length=60, null=True, verbose_name='产生费用')),
                ('end_free_time', models.DateTimeField(blank=True, null=True, verbose_name='清算费用时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us', to='My_Parking_Charge.user_info', verbose_name='用户外键')),
            ],
        ),
    ]
